- hosts: all
  gather_facts: no
  remote_user: ubuntu

  tasks:
  - name: Hot-unplug all virtual CPUS
    # Source: https://aws.amazon.com/blogs/compute/disabling-intel-hyper-threading-technology-on-amazon-linux/
    shell: |
      for cpunum in $(cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | cut -s -d, -f2- | tr ',' '\n' | sort -un)
      do
        echo 0 > /sys/devices/system/cpu/cpu$cpunum/online
      done
    become: true

  - name: Wait for unattended-upgrades to finish
    shell: while pgrep unattended; do sleep 10; done;

  - name: Install cpuset & numactl
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - cpuset
      - numactl
    become:
      true
    retries: 50
    delay: 3

  - name: Set up cgroups
    shell: |
        cset set --destroy wallaroo || true
        cset set --cpu=0-{{ workers_per_machine }} --set=wallaroo
    become: true
    retries: 50
    delay: 3
