- hosts: all
  gather_facts: no
  remote_user: ubuntu

  tasks:
  - name: Wait 600 seconds for target connection to become reachable/usable
    wait_for_connection:

  - name: clean slate
    shell: |
      ps -ef | grep -v grep | grep -w {{ item }} | awk '{print $2}' | xargs kill -9
    with_items:
      - machida
      - data_receiver
      - metrics_reporter
      - send.py
    become: true

  - name: upload app.zip
    copy:
      src: ../app.zip
      dest: /tmp/app.zip

  - name: Unpack code
    shell: |
      mkdir -p {{ app_dir }} && unzip -o -d {{ app_dir }} /tmp/app.zip

  - name: Install requirements
    shell: |
      cd {{ app_dir }} && pip install -U -vvv -r requirements.txt > piplog 2>&1
    become:
      true
