# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pricealertweb', '0002_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
