# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricealertweb', '0003_auto_20180815_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
