# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricealertweb', '0004_alerts_alert_sent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
    ]
