# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricealertweb', '0005_auto_20180820_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alert_sent',
            new_name='sent',
        ),
    ]
